### ISSUE TITLE
Apple Pay v. In-App Purchase API

### ISSUE THREAD

**Issue by drefiuza** [uchicago-mobi/2015-Spring-Forum#21]
Here's the page I pulled up in class in case anyone wants to check it out in more detail:

https://support.stripe.com/questions/apple-and-stripe-tos-and-fees

**Comment by xiaoyifan** [comment]
Thanks for that, quite curious about the payment programming

**Comment by tabinks** [comment]
If anyone is interested in seeing an example of Apple Pay integrated into an app, checkout out this app:
[Highball - Share and Collect Cocktail Recipes - Studio Neat](https://itunes.apple.com/us/app/highball-share-collect-cocktail/id973319934?mt=8&uo=4&at=11laH5).  You can buy physical goods for helping to make cocktails from the app and, something I've never seen before, a "tip" jar where you can just give them money.

The app also does a neat trick with QR codes embedded in images to share data.  It allows you to post images, instead of text, to social networks to share drink recipes.  Users can save the image and extract the recipe from a QR code embedded in the image.  That's pretty slick thinking.
