### ISSUE TITLE
CloudKit Question

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Spring-Forum#70]
I cannot save records to CloudKit unless iCloud Drive is turned on.  Will it be the case for every user that not only do they have to be signed in to iCloud, but they also have to be using iCloud Drive?  

Found this on stackoverflow: 

"I found I couldn't connect to CloudKit at all until I upgrade to iCloud drive; in my case I was able to do it in the simulator. Also you can't log in to iCloud on the simulator if you have 2-factor authentication set up, it seems."

Edit: It looks like I can fetch data from the device with iCloud Drive off.  I just cannot write to CloudKit with it off.

**Comment by tabinks** [comment]
I know that anyone can read off CloudKit regardless of iCloud account/status, but I am not sure about the need to enable iCloud Drive.   

One thing to note is that iCloud Drive is the default storage since iOS8.  The need to explicitly "turn on" iCloud drive was during the transition from iOS7 to iOS8.

I will investigate further.
