### ISSUE TITLE
Marketing Materials Needed for Final Project?

### ISSUE THREAD

**Issue by alextsu** [uchicago-mobi/2015-Spring-Forum#94]
Just wanted to check in to see if the Executive Summary and Marketing Materials are going to be necessary for the final project. Given that we've done it once before and that we've got less time than last quarter to work on these projects, I'd love to skip these in order to devote more time on my app itself. What are your thoughts?

**Comment by tabinks** [comment]
While it is a compelling argument, I really think that taking the time to do the marketing materials really forces you to think about your app in a different way than just coding.  Figuring out how to present your app to the world (and making sure that they get it) is one of those barriers that all the Core Data and Swift in the world can't solve.

However, since it is not part of a formal App Store submission, I will **remove** the _Executive Summary_ requirement from the marketing materials.  This way everything you are working on for the formal project will be towards the goal of getting your app "App Store Ready".

**Comment by alextsu** [comment]
Great. Thanks for the response Andrew!
